package cssfilter

import "regexp"

var regexpURLJavascript = regexp.MustCompile(`(?i)javascript\s*:`)

type WhiteListCheck struct {
	Allow bool                    // check === true
	Func  func(value string) bool // check is function
	Reg   *regexp.Regexp          // check is regexp
}

var DefaultCssWhiteList = map[string]WhiteListCheck{
	"align-content":               {Allow: false},
	"align-items":                 {Allow: false},
	"align-self":                  {Allow: false},
	"alignment-adjust":            {Allow: false},
	"alignment-baseline":          {Allow: false},
	"all":                         {Allow: false},
	"anchor-point":                {Allow: false},
	"animation":                   {Allow: false},
	"animation-delay":             {Allow: false},
	"animation-direction":         {Allow: false},
	"animation-duration":          {Allow: false},
	"animation-fill-mode":         {Allow: false},
	"animation-iteration-count":   {Allow: false},
	"animation-name":              {Allow: false},
	"animation-play-state":        {Allow: false},
	"animation-timing-function":   {Allow: false},
	"azimuth":                     {Allow: false},
	"backface-visibility":         {Allow: false},
	"background":                  {Allow: true},
	"background-attachment":       {Allow: true},
	"background-clip":             {Allow: true},
	"background-color":            {Allow: true},
	"background-image":            {Allow: true},
	"background-origin":           {Allow: true},
	"background-position":         {Allow: true},
	"background-repeat":           {Allow: true},
	"background-size":             {Allow: true},
	"baseline-shift":              {Allow: false},
	"binding":                     {Allow: false},
	"bleed":                       {Allow: false},
	"bookmark-label":              {Allow: false},
	"bookmark-level":              {Allow: false},
	"bookmark-state":              {Allow: false},
	"border":                      {Allow: true},
	"border-bottom":               {Allow: true},
	"border-bottom-color":         {Allow: true},
	"border-bottom-left-radius":   {Allow: true},
	"border-bottom-right-radius":  {Allow: true},
	"border-bottom-style":         {Allow: true},
	"border-bottom-width":         {Allow: true},
	"border-collapse":             {Allow: true},
	"border-color":                {Allow: true},
	"border-image":                {Allow: true},
	"border-image-outset":         {Allow: true},
	"border-image-repeat":         {Allow: true},
	"border-image-slice":          {Allow: true},
	"border-image-source":         {Allow: true},
	"border-image-width":          {Allow: true},
	"border-left":                 {Allow: true},
	"border-left-color":           {Allow: true},
	"border-left-style":           {Allow: true},
	"border-left-width":           {Allow: true},
	"border-radius":               {Allow: true},
	"border-right":                {Allow: true},
	"border-right-color":          {Allow: true},
	"border-right-style":          {Allow: true},
	"border-right-width":          {Allow: true},
	"border-spacing":              {Allow: true},
	"border-style":                {Allow: true},
	"border-top":                  {Allow: true},
	"border-top-color":            {Allow: true},
	"border-top-left-radius":      {Allow: true},
	"border-top-right-radius":     {Allow: true},
	"border-top-style":            {Allow: true},
	"border-top-width":            {Allow: true},
	"border-width":                {Allow: true},
	"bottom":                      {Allow: false},
	"box-decoration-break":        {Allow: true},
	"box-shadow":                  {Allow: true},
	"box-sizing":                  {Allow: true},
	"box-snap":                    {Allow: true},
	"box-suppress":                {Allow: true},
	"break-after":                 {Allow: true},
	"break-before":                {Allow: true},
	"break-inside":                {Allow: true},
	"caption-side":                {Allow: false},
	"chains":                      {Allow: false},
	"clear":                       {Allow: true},
	"clip":                        {Allow: false},
	"clip-path":                   {Allow: false},
	"clip-rule":                   {Allow: false},
	"color":                       {Allow: true},
	"color-interpolation-filters": {Allow: true},
	"column-count":                {Allow: false},
	"column-fill":                 {Allow: false},
	"column-gap":                  {Allow: false},
	"column-rule":                 {Allow: false},
	"column-rule-color":           {Allow: false},
	"column-rule-style":           {Allow: false},
	"column-rule-width":           {Allow: false},
	"column-span":                 {Allow: false},
	"column-width":                {Allow: false},
	"columns":                     {Allow: false},
	"contain":                     {Allow: false},
	"content":                     {Allow: false},
	"counter-increment":           {Allow: false},
	"counter-reset":               {Allow: false},
	"counter-set":                 {Allow: false},
	"crop":                        {Allow: false},
	"cue":                         {Allow: false},
	"cue-after":                   {Allow: false},
	"cue-before":                  {Allow: false},
	"cursor":                      {Allow: false},
	"direction":                   {Allow: false},
	"display":                     {Allow: true},
	"display-inside":              {Allow: true},
	"display-list":                {Allow: true},
	"display-outside":             {Allow: true},
	"dominant-baseline":           {Allow: false},
	"elevation":                   {Allow: false},
	"empty-cells":                 {Allow: false},
	"filter":                      {Allow: false},
	"flex":                        {Allow: false},
	"flex-basis":                  {Allow: false},
	"flex-direction":              {Allow: false},
	"flex-flow":                   {Allow: false},
	"flex-grow":                   {Allow: false},
	"flex-shrink":                 {Allow: false},
	"flex-wrap":                   {Allow: false},
	"float":                       {Allow: false},
	"float-offset":                {Allow: false},
	"flood-color":                 {Allow: false},
	"flood-opacity":               {Allow: false},
	"flow-from":                   {Allow: false},
	"flow-into":                   {Allow: false},
	"font":                        {Allow: true},
	"font-family":                 {Allow: true},
	"font-feature-settings":       {Allow: true},
	"font-kerning":                {Allow: true},
	"font-language-override":      {Allow: true},
	"font-size":                   {Allow: true},
	"font-size-adjust":            {Allow: true},
	"font-stretch":                {Allow: true},
	"font-style":                  {Allow: true},
	"font-synthesis":              {Allow: true},
	"font-variant":                {Allow: true},
	"font-variant-alternates":     {Allow: true},
	"font-variant-caps":           {Allow: true},
	"font-variant-east-asian":     {Allow: true},
	"font-variant-ligatures":      {Allow: true},
	"font-variant-numeric":        {Allow: true},
	"font-variant-position":       {Allow: true},
	"font-weight":                 {Allow: true},
	"gap":                         {Allow: false},
	"grid":                        {Allow: false},
	"grid-area":                   {Allow: false},
	"grid-auto-columns":           {Allow: false},
	"grid-auto-flow":              {Allow: false},
	"grid-auto-rows":              {Allow: false},
	"grid-column":                 {Allow: false},
	"grid-column-end":             {Allow: false},
	"grid-column-start":           {Allow: false},
	"grid-row":                    {Allow: false},
	"grid-row-end":                {Allow: false},
	"grid-row-start":              {Allow: false},
	"grid-template":               {Allow: false},
	"grid-template-areas":         {Allow: false},
	"grid-template-columns":       {Allow: false},
	"grid-template-rows":          {Allow: false},
	"hanging-punctuation":         {Allow: false},
	"height":                      {Allow: true},
	"hyphens":                     {Allow: false},
	"icon":                        {Allow: false},
	"image-orientation":           {Allow: false},
	"image-resolution":            {Allow: false},
	"ime-mode":                    {Allow: false},
	"initial-letters":             {Allow: false},
	"inline-box-align":            {Allow: false},
	"justify-content":             {Allow: false},
	"justify-items":               {Allow: false},
	"justify-self":                {Allow: false},
	"left":                        {Allow: false},
	"letter-spacing":              {Allow: true},
	"lighting-color":              {Allow: true},
	"line-box-contain":            {Allow: false},
	"line-break":                  {Allow: false},
	"line-grid":                   {Allow: false},
	"line-height":                 {Allow: false},
	"line-snap":                   {Allow: false},
	"line-stacking":               {Allow: false},
	"line-stacking-ruby":          {Allow: false},
	"line-stacking-shift":         {Allow: false},
	"line-stacking-strategy":      {Allow: false},
	"list-style":                  {Allow: true},
	"list-style-image":            {Allow: true},
	"list-style-position":         {Allow: true},
	"list-style-type":             {Allow: true},
	"margin":                      {Allow: true},
	"margin-bottom":               {Allow: true},
	"margin-left":                 {Allow: true},
	"margin-right":                {Allow: true},
	"margin-top":                  {Allow: true},
	"marker-offset":               {Allow: false},
	"marker-side":                 {Allow: false},
	"marks":                       {Allow: false},
	"mask":                        {Allow: false},
	"mask-box":                    {Allow: false},
	"mask-box-outset":             {Allow: false},
	"mask-box-repeat":             {Allow: false},
	"mask-box-slice":              {Allow: false},
	"mask-box-source":             {Allow: false},
	"mask-box-width":              {Allow: false},
	"mask-clip":                   {Allow: false},
	"mask-image":                  {Allow: false},
	"mask-origin":                 {Allow: false},
	"mask-position":               {Allow: false},
	"mask-repeat":                 {Allow: false},
	"mask-size":                   {Allow: false},
	"mask-source-type":            {Allow: false},
	"mask-type":                   {Allow: false},
	"max-height":                  {Allow: true},
	"max-lines":                   {Allow: false},
	"max-width":                   {Allow: true},
	"min-height":                  {Allow: true},
	"min-width":                   {Allow: true},
	"move-to":                     {Allow: false},
	"nav-down":                    {Allow: false},
	"nav-index":                   {Allow: false},
	"nav-left":                    {Allow: false},
	"nav-right":                   {Allow: false},
	"nav-up":                      {Allow: false},
	"object-fit":                  {Allow: false},
	"object-position":             {Allow: false},
	"opacity":                     {Allow: false},
	"order":                       {Allow: false},
	"orphans":                     {Allow: false},
	"outline":                     {Allow: false},
	"outline-color":               {Allow: false},
	"outline-offset":              {Allow: false},
	"outline-style":               {Allow: false},
	"outline-width":               {Allow: false},
	"overflow":                    {Allow: false},
	"overflow-wrap":               {Allow: false},
	"overflow-x":                  {Allow: false},
	"overflow-y":                  {Allow: false},
	"padding":                     {Allow: true},
	"padding-bottom":              {Allow: true},
	"padding-left":                {Allow: true},
	"padding-right":               {Allow: true},
	"padding-top":                 {Allow: true},
	"page":                        {Allow: false},
	"page-break-after":            {Allow: false},
	"page-break-before":           {Allow: false},
	"page-break-inside":           {Allow: false},
	"page-policy":                 {Allow: false},
	"pause":                       {Allow: false},
	"pause-after":                 {Allow: false},
	"pause-before":                {Allow: false},
	"perspective":                 {Allow: false},
	"perspective-origin":          {Allow: false},
	"pitch":                       {Allow: false},
	"pitch-range":                 {Allow: false},
	"play-during":                 {Allow: false},
	"position":                    {Allow: false},
	"presentation-level":          {Allow: false},
	"quotes":                      {Allow: false},
	"region-fragment":             {Allow: false},
	"resize":                      {Allow: false},
	"rest":                        {Allow: false},
	"rest-after":                  {Allow: false},
	"rest-before":                 {Allow: false},
	"richness":                    {Allow: false},
	"right":                       {Allow: false},
	"rotation":                    {Allow: false},
	"rotation-point":              {Allow: false},
	"row-gap":                     {Allow: false},
	"ruby-align":                  {Allow: false},
	"ruby-merge":                  {Allow: false},
	"ruby-position":               {Allow: false},
	"shape-image-threshold":       {Allow: false},
	"shape-outside":               {Allow: false},
	"shape-margin":                {Allow: false},
	"size":                        {Allow: false},
	"speak":                       {Allow: false},
	"speak-as":                    {Allow: false},
	"speak-header":                {Allow: false},
	"speak-numeral":               {Allow: false},
	"speak-punctuation":           {Allow: false},
	"speech-rate":                 {Allow: false},
	"stress":                      {Allow: false},
	"string-set":                  {Allow: false},
	"tab-size":                    {Allow: false},
	"table-layout":                {Allow: false},
	"text-align":                  {Allow: true},
	"text-align-last":             {Allow: true},
	"text-combine-upright":        {Allow: true},
	"text-decoration":             {Allow: true},
	"text-decoration-color":       {Allow: true},
	"text-decoration-line":        {Allow: true},
	"text-decoration-skip":        {Allow: true},
	"text-decoration-style":       {Allow: true},
	"text-emphasis":               {Allow: true},
	"text-emphasis-color":         {Allow: true},
	"text-emphasis-position":      {Allow: true},
	"text-emphasis-style":         {Allow: true},
	"text-height":                 {Allow: true},
	"text-indent":                 {Allow: true},
	"text-justify":                {Allow: true},
	"text-orientation":            {Allow: true},
	"text-overflow":               {Allow: true},
	"text-shadow":                 {Allow: true},
	"text-space-collapse":         {Allow: true},
	"text-transform":              {Allow: true},
	"text-underline-position":     {Allow: true},
	"text-wrap":                   {Allow: true},
	"top":                         {Allow: false},
	"transform":                   {Allow: false},
	"transform-origin":            {Allow: false},
	"transform-style":             {Allow: false},
	"transition":                  {Allow: false},
	"transition-delay":            {Allow: false},
	"transition-duration":         {Allow: false},
	"transition-property":         {Allow: false},
	"transition-timing-function":  {Allow: false},
	"unicode-bidi":                {Allow: false},
	"vertical-align":              {Allow: false},
	"visibility":                  {Allow: false},
	"voice-balance":               {Allow: false},
	"voice-duration":              {Allow: false},
	"voice-family":                {Allow: false},
	"voice-pitch":                 {Allow: false},
	"voice-range":                 {Allow: false},
	"voice-rate":                  {Allow: false},
	"voice-stress":                {Allow: false},
	"voice-volume":                {Allow: false},
	"volume":                      {Allow: false},
	"white-space":                 {Allow: false},
	"widows":                      {Allow: false},
	"width":                       {Allow: true},
	"will-change":                 {Allow: false},
	"word-break":                  {Allow: true},
	"word-spacing":                {Allow: true},
	"word-wrap":                   {Allow: true},
	"wrap-flow":                   {Allow: false},
	"wrap-through":                {Allow: false},
	"writing-mode":                {Allow: false},
	"z-index":                     {Allow: false},
}

type StyleAttrOption struct {
	SourcePosition int
	Position       int
	Source         string
	IsWhite        bool
}

type CssOption struct {
	WhiteList map[string]WhiteListCheck

	OnAttr func(name, value string, options StyleAttrOption) *string

	OnIgnoreAttr func(name, value string, options StyleAttrOption) *string

	SafeAttrValue func(name, value string) string
}

// safeAttrValue 过滤属性值
func SafeAttrValue(name, value string) string {
	// 如果匹配 javascript:（忽略大小写）
	if regexpURLJavascript.MatchString(value) {
		return ""
	}
	return value
}
